# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Deartoday' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Deartoday

  pod 'Moya', '~> 15.0'
  pod 'Kingfisher', '~> 7.0'

  pod 'SnapKit', '~> 5.0.0'
  pod 'Then'

  pod 'lottie-ios'

  pod 'Firebase/Messaging'

end
